version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: taskstorm_backend
    ports:
      - "3000:3000"
    volumes:
      - "./backend/database/database.db:/app/backend/database/database.db"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  frontend:
    build: ./frontend
    container_name: taskstorm_frontend
    ports:
      - "4000:4000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3000
      - VUE_APP_BACKEND_URL=http://localhost:3000
